FROM oven/bun:latest

WORKDIR /app

COPY turbo.json package.json bun.lock ./

COPY apps/web/package.json apps/web/tsconfig.json apps/web/next.config.js ./apps/web/

COPY packages/typescript-config ./packages/typescript-config
COPY packages/eslint-config ./packages/eslint-config
COPY packages/db/package.json packages/db/tsconfig.json ./packages/db/
COPY packages/ui/package.json packages/ui/tsconfig.json ./packages/ui/

RUN bun install 

COPY apps/web/app ./apps/web/app
COPY apps/web/public ./apps/web/public


COPY packages/db/prisma packages/db/index.ts ./packages/db/
COPY packages/ui/src ./packages/ui/src

ARG DATABASE_URL

RUN echo DATABASE_URL

RUN cd packages/db && touch .env && echo DATABASE_URL=$DATABASE_URL >> .env && cd ../..


RUN bun run db:generate
RUN bun run build

EXPOSE 8000

CMD ["bun", "run", "start:web"]
