FROM node:22-alpine

RUN npm install -g bun

WORKDIR /app

COPY turbo.json package.json bun.lock ./

COPY apps/websocket/package.json apps/websocket/tsconfig.json ./apps/websocket/

COPY packages/typescript-config ./packages/typescript-config

COPY packages/db/package.json packages/db/tsconfig.json ./packages/db/

RUN bun install 

COPY apps/websocket/index.ts ./apps/websocket/index.ts

COPY packages/db/prisma packages/db/index.ts ./packages/db/

RUN bun run db:generate
RUN bun run build

ENV NODE_ENV=production PORT=3002
EXPOSE 3002

CMD ["bun","run","start:websocket"]